############# Spanish navigation ##############

# main menu
[[main]]
name = "Inicio"  # Spanish for "Home"
url = "/es/"     # The base URL for Spanish pages
weight = 1

[[main]]
name = "Acerca de"  # Spanish for "About"
url = "/es/about"   # URL for the "About" page in Spanish
weight = 2

[[main]]
name = "Elementos"  # Spanish for "Elements"
url = "/es/elements"
weight = 3

[[main]]
weight = 4
name = "Páginas"  # Spanish for "Pages"

[[main]]
parent = "Páginas"
name = "Blog"
url = "/es/blog"

[[main]]
parent = "Páginas"
name = "Contacto"  # Spanish for "Contact"
url = "/es/contact"

[[main]]
parent = "Páginas"
name = "Autores"  # Spanish for "Authors"
url = "/es/authors"

[[main]]
parent = "Páginas"
name = "Categorías"  # Spanish for "Categories"
url = "/es/categories"

[[main]]
parent = "Páginas"
name = "Página 404"  # Spanish for "404 Page"
url = "/es/404"


# footer menu
[[footer]]
name = "Acerca de"
url = "/es/about"
weight = 1

[[footer]]
name = "Elementos"
url = "/es/elements"
weight = 2

[[footer]]
name = "Política de Privacidad"  # Spanish for "Privacy Policy"
url = "/es/privacy-policy"
weight = 3
